name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Creating and activating virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install dvc[gs]
          pip install -r requirements_test.txt
      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-track --force
          pytest